import { createHash } from 'node:crypto';
import { readFile, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
import { VERSION } from '../version.js';

export interface SpecDraft {
  schemaVersion: string;
  specKind: 'authoring-draft';
  status: 'draft';
  generatedAt: string;
  source: {
    kind: 'file' | 'inline' | 'stdin';
    path: string | null;
    sha256: string;
    headings: readonly string[];
    text: string;
  };
  unknowns: readonly string[];
}

export interface SpecCheckIssue {
  code:
    | 'missing-section'
    | 'missing-provenance'
    | 'missing-criterion'
    | 'missing-verification'
    | 'missing-taste-review'
    | 'missing-release-boundary'
    | 'unresolved-input'
    | 'not-accepted';
  message: string;
}

export interface SpecCheckResult {
  schemaVersion: string;
  specKind: 'spec-check';
  path: string;
  readiness: 'ready' | 'draft' | 'invalid';
  accepted: boolean;
  sections: Readonly<Record<string, boolean>>;
  issues: readonly SpecCheckIssue[];
}

const MAX_INPUT_BYTES = 2 * 1024 * 1024;

export async function createSpecDraft(
  input: string,
  stdin?: NodeJS.ReadableStream,
): Promise<SpecDraft> {
  const source = await readSource(input, stdin);
  if (!source.text.trim()) throw new Error('spec-create: input is empty.');
  if (source.text.includes('\0'))
    throw new Error('spec-create: binary input is not supported.');
  if (Buffer.byteLength(source.text, 'utf8') > MAX_INPUT_BYTES)
    throw new Error('spec-create: input is larger than the 2 MiB local limit.');

  return {
    schemaVersion: VERSION,
    specKind: 'authoring-draft',
    status: 'draft',
    generatedAt: new Date().toISOString(),
    source: {
      kind: source.kind,
      path: source.path,
      sha256: createHash('sha256').update(source.text).digest('hex'),
      headings: extractHeadings(source.text),
      text: source.text,
    },
    unknowns: [
      'The owner, target user, and user job require human confirmation.',
      'The desired outcome, non-goals, constraints, and forbidden behavior require human confirmation.',
      'Acceptance evidence, verification commands, and fixtures require a named implementation owner.',
      'Taste, usability, accessibility, and operational quality require a human rubric and review.',
      'Release target, compatibility, security, rollback, and ship authority require human confirmation.',
    ],
  };
}

export function renderSpecDraftMarkdown(draft: SpecDraft): string {
  const headings = draft.source.headings.length
    ? draft.source.headings.map((heading) => `- ${heading}`)
    : ['- None observed.'];
  const unknowns = draft.unknowns.map((unknown) => `- ${unknown}`);
  const sourceFence = markdownFence(draft.source.text);
  const sourceLabel = draft.source.path ?? draft.source.kind;
  return [
    '# SPEC.md',
    '',
    '> Draft generated by SpecPort. Observed source is preserved; intent and ship authority remain human-owned.',
    '',
    '- Status: **draft — human confirmation required**',
    `- Source: \`${sourceLabel}\``,
    `- Source SHA-256: \`${draft.source.sha256}\``,
    `- Generated: \`${draft.generatedAt}\``,
    '',
    '## Intent',
    '',
    '- Owner: `[NEEDS HUMAN INPUT]`',
    '- Target user and job: `[NEEDS HUMAN INPUT]`',
    '- Desired outcome: `[NEEDS HUMAN INPUT]`',
    '- Non-goals: `[NEEDS HUMAN INPUT]`',
    '- Constraints and forbidden behavior: `[NEEDS HUMAN INPUT]`',
    '',
    '## Product behavior',
    '',
    '- Describe the primary workflow, important edge cases, failure semantics, and user-visible boundaries.',
    '- Separate observed source behavior from proposed product behavior.',
    '',
    '## Acceptance',
    '',
    '- Add scenario criteria with IDs, expected behavior, evidence, risk, and explicit forbidden behavior.',
    '- Example: `AC-001`: Given [input], when [action], then [observable result], evidenced by [test or review].',
    '',
    '## Verification',
    '',
    '- Declare exact commands, fixtures, environments, and what each check does not prove.',
    '- A skipped or stale check is not a pass.',
    '',
    '## Taste and human review',
    '',
    '- Reviewer: `[NEEDS HUMAN INPUT]`',
    '- Rubric: `[NEEDS HUMAN INPUT]`',
    '- Evidence: the real user flow, visual review, listening notes, writing review, or operational exercise appropriate to the product.',
    '',
    '## Release',
    '',
    '- Target and artifact: `[NEEDS HUMAN INPUT]`',
    '- Version and compatibility: `[NEEDS HUMAN INPUT]`',
    '- Security, privacy, observability, rollback, and ship authority: `[NEEDS HUMAN INPUT]`',
    '',
    '## Observed source headings',
    '',
    ...headings,
    '',
    '## Open decisions',
    '',
    ...unknowns,
    '',
    '## Source material preserved by SpecPort',
    '',
    sourceFence.open,
    draft.source.text,
    sourceFence.close,
    '',
  ].join('\n');
}

export async function checkSpecFile(path: string): Promise<SpecCheckResult> {
  const absolute = resolve(path);
  let text: string;
  try {
    text = await readFile(absolute, 'utf8');
  } catch (error) {
    return {
      schemaVersion: VERSION,
      specKind: 'spec-check',
      path: absolute,
      readiness: 'invalid',
      accepted: false,
      sections: {},
      issues: [
        {
          code: 'missing-provenance',
          message: `Could not read spec: ${error instanceof Error ? error.message : String(error)}`,
        },
      ],
    };
  }

  const sections = {
    intent: hasHeading(text, 'intent'),
    behavior: hasHeading(text, 'behavior|workflow|capability'),
    acceptance: hasHeading(text, 'acceptance|success|criteria'),
    verification: hasHeading(text, 'verification|checks|tests'),
    taste: hasHeading(text, 'taste|human review|rubric'),
    release: hasHeading(text, 'release|ship|deployment'),
  };
  const issues: SpecCheckIssue[] = [];
  for (const [name, present] of Object.entries(sections)) {
    if (!present)
      issues.push({
        code: 'missing-section',
        message: `Required section is missing: ${name}.`,
      });
  }
  if (!/source|provenance|generated by|repository identity/i.test(text))
    issues.push({
      code: 'missing-provenance',
      message: 'The spec does not declare where its facts came from.',
    });
  if (!/(AC-\d+|Given\b.+\bwhen\b.+\bthen\b|acceptance criterion)/is.test(text))
    issues.push({
      code: 'missing-criterion',
      message: 'Add at least one observable acceptance criterion.',
    });
  if (
    !/(npm\s+(run|test)|pytest|cargo\s+test|go\s+test|verification command|check\s*:`?)/i.test(
      text,
    )
  )
    issues.push({
      code: 'missing-verification',
      message: 'Declare at least one repeatable verification command.',
    });
  if (!/reviewer\s*:|human reviewer|taste rubric|rubric\s*:/i.test(text))
    issues.push({
      code: 'missing-taste-review',
      message: 'Name a human reviewer and a product-specific taste rubric.',
    });
  if (
    !/(release target|target and artifact|compatibility|rollback)/i.test(text)
  )
    issues.push({
      code: 'missing-release-boundary',
      message:
        'Declare the release artifact, compatibility, and rollback boundary.',
    });
  if (/\[NEEDS HUMAN INPUT\]|\bTBD\b|\bTODO\b/i.test(text))
    issues.push({
      code: 'unresolved-input',
      message: 'The spec still contains unresolved human decisions.',
    });

  const accepted = /status\s*:\s*\**\s*(accepted|ready|shippable)\b/i.test(
    text,
  );
  if (!accepted)
    issues.push({
      code: 'not-accepted',
      message:
        'The spec does not explicitly declare an accepted or shippable status.',
    });

  const structuralIssue = issues.some((issue) =>
    [
      'missing-section',
      'missing-provenance',
      'missing-criterion',
      'missing-verification',
    ].includes(issue.code),
  );
  return {
    schemaVersion: VERSION,
    specKind: 'spec-check',
    path: absolute,
    readiness: structuralIssue ? 'invalid' : issues.length ? 'draft' : 'ready',
    accepted,
    sections,
    issues,
  };
}

export function renderSpecCheckHuman(result: SpecCheckResult): string {
  const lines = [
    `SPEC       ${result.readiness}`,
    `ACCEPTED   ${result.accepted ? 'yes' : 'no'}`,
    `FILE       ${result.path}`,
    `SECTIONS   ${Object.values(result.sections).filter(Boolean).length}/${Object.keys(result.sections).length}`,
  ];
  if (result.issues.length) {
    lines.push(
      ...result.issues.map(
        (issue) => `ISSUE      ${issue.code}: ${issue.message}`,
      ),
    );
  } else {
    lines.push('ISSUE      none');
  }
  return `${lines.join('\n')}\n`;
}

async function readSource(
  input: string,
  stdin?: NodeJS.ReadableStream,
): Promise<{
  kind: SpecDraft['source']['kind'];
  path: string | null;
  text: string;
}> {
  if (input === '-') {
    if (!stdin) throw new Error('spec-create: stdin is unavailable.');
    return { kind: 'stdin', path: null, text: await readStream(stdin) };
  }
  try {
    const info = await stat(input);
    if (info.isFile()) {
      if (info.size > MAX_INPUT_BYTES)
        throw new Error(
          'spec-create: input is larger than the 2 MiB local limit.',
        );
      return {
        kind: 'file',
        path: resolve(input),
        text: await readFile(input, 'utf8'),
      };
    }
    throw new Error(`spec-create: input path is not a file: ${resolve(input)}`);
  } catch (error) {
    if (error instanceof Error && error.message.startsWith('spec-create:'))
      throw error;
    if (!isNodeError(error, 'ENOENT')) {
      throw new Error(
        `spec-create: could not read input: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }
  return { kind: 'inline', path: null, text: input };
}

async function readStream(stdin: NodeJS.ReadableStream): Promise<string> {
  const chunks: string[] = [];
  let byteLength = 0;
  for await (const chunk of stdin as AsyncIterable<Buffer | string>) {
    const text = typeof chunk === 'string' ? chunk : chunk.toString('utf8');
    chunks.push(text);
    byteLength += Buffer.byteLength(text, 'utf8');
    if (byteLength > MAX_INPUT_BYTES)
      throw new Error(
        'spec-create: input is larger than the 2 MiB local limit.',
      );
  }
  return chunks.join('');
}

function extractHeadings(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => /^\s{0,3}#{1,6}\s+(.+?)\s*$/.exec(line)?.[1])
    .filter((heading): heading is string => Boolean(heading))
    .slice(0, 30);
}

function markdownFence(text: string): { open: string; close: string } {
  const runs = [...text.matchAll(/`+/g)].map((match) => match[0]?.length ?? 0);
  const length = Math.max(3, ...runs) + 1;
  const fence = '`'.repeat(length);
  return { open: `${fence}text`, close: fence };
}

function hasHeading(text: string, pattern: string): boolean {
  const expression = new RegExp(`^\\s{0,3}#{1,6}\\s+.*(?:${pattern}).*$`, 'im');
  return expression.test(text);
}

function isNodeError(error: unknown, code: string): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    error.code === code
  );
}
